name: Run tests

on:
  - push
  - pull_request

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', 8.1, 8.2, 8.3]
        laravel: ['8.*', '9.*', '10.*', '11.*', '12.*']
        stability: [prefer-stable]
        exclude:
          - laravel: 8.*
            php: 8.2
          - laravel: 8.*
            php: 8.3
          - laravel: 9.*
            php: 8.3
          - laravel: 10.*
            php: '8.0'
          - laravel: 11.*
            php: '8.0'
          - laravel: 11.*
            php: 8.1
          - laravel: 12.*
            php: '8.0'
          - laravel: 12.*
            php: 8.1
        include:
          - laravel: 8.*
            phpunit: ^9.5
          - laravel: 9.*
            phpunit: ^9.5
          - laravel: 10.*
            phpunit: ^10.5
          - laravel: 11.*
            phpunit: ^10.5
          - laravel: 12.*
            phpunit: ^11.5

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch 10 commits or Scrutinizer will throw
          fetch-depth: 10

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ matrix.stability }}-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ matrix.stability }}-

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --configuration=${{ matrix.phpunit == '^9.5' && 'phpunit-9.xml' || 'phpunit.xml' }} --coverage-text --coverage-clover=coverage.clover

      - name: Upload Scrutinizer coverage
        uses: sudo-bot/action-scrutinizer@latest
        # Do not run this step on forked versions of the main repository (example: contributor forks)
        if: "matrix.laravel == '9.*' && github.repository == 'swisnl/json-api-client-laravel'"
        with:
          cli-args: --format=php-clover coverage.clover --revision=${{ github.event.pull_request.head.sha || github.sha }}
